### ISSUE TITLE
RSS feed does't work

### ISSUE THREAD

**Issue by yurtaev** [Beraliv/beraliv.dev#103]
https://blog.beraliv.dev/rss.xml return 404

**Comment by Beraliv** [comment]
@yurtaev thanks for reporting, I didn't configure it yet

**Comment by yurtaev** [comment]
Yep 👍  I just wanted to subscribe by RSS because I found the link`<link rel="alternate" type="application/rss+xml" href="/rss.xml"/>` in sources.

**Comment by Beraliv** [comment]
I need to configure gatsby RSS plugin and it will be available

Hopefully will do in 2 weeks

**Comment by Beraliv** [comment]
@yurtaev will be fixed here – https://github.com/Beraliv/beraliv.dev/pull/144

**Comment by Beraliv** [comment]
Done ✅

**Comment by yurtaev** [comment]
I think [the line](https://github.com/Beraliv/beraliv.dev/pull/144/files#diff-14fe5dc4f42073d894e8ff2ac22b0b1ae6d8b6b42693d56903a56249ca4e00b4R100) generate a double slash:

![CleanShot 2021-06-15 at 16 21 54](https://user-images.githubusercontent.com/444503/122018846-d211de00-cdf5-11eb-9357-15de484941db.jpg)
